casco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flash_card.urls')),
]

flash_card/urls.py
from django.urls import path
from .views import (
    DeckCreateView,
    DeckListView,
    DeckDetailView,
    DeckUpdateView,
    DeckDeleteView,
    CardCreateView,
    CardUpdateView,
    CardDeleteView,
    card_create_view,
)

app_name = 'flash_card'

urlpatterns = [
    path('decks/', DeckListView.as_view(), name='deck-list'),
    path('decks/<int:pk>/', DeckDetailView.as_view(), name='deck-detail'),
    path('decks/create/', DeckCreateView.as_view(), name='deck-create'),
    path('decks/<int:pk>/card/create/', CardCreateView.as_view(), name='card-create'),
    path('decks/<int:pk>/update/', DeckUpdateView.as_view(), name='deck-update'),
    path('decks/<int:pk>/delete/', DeckDeleteView.as_view(), name='deck-delete'),
    path('decks/<int:pk>/card/<int:id>/update/', CardUpdateView.as_view(), name='card-update'),
    path('decks/<int:pk>/card/<int:id>/delete/', CardDeleteView.as_view(), name='card-delete'),
]

flash_card/models.py
from django.db import models


class Deck(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='static/%Y/%m/%d', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    view = models.IntegerField(default=0, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def __repr__(self):
        return self.__str__()

    def get_image_folder(self):
        return str(self.image)[6:]

    class Meta:
        ordering = ['updated_at']


class Card(models.Model):
    title = models.CharField(max_length=200)
    answer = models.CharField(max_length=300)
    icon = models.ImageField(upload_to='static/photos/icons/%Y/%m/%d', null=True, blank=True)
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    view = models.IntegerField(default=0, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def __repr__(self):
        return self.__str__()

    def get_icon_forder(self):
        return str(self.image)[6:]

    class Meta:
        ordering = ['-updated_at']

flash_card/forms.py
from django import forms
from .models import Deck, Card


class DeckCreateForm(forms.ModelForm):
    class Meta:
        model = Deck
        fields = [
            'title',
            'image',
            'description'
        ]


class CardCreateForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = [
            'title',
            'answer',
            'icon'         
        ]

flash_card/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Deck, Card
from .forms import DeckCreateForm, CardCreateForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

    
class DeckCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'deck_create.html'
    form_class = DeckCreateForm
    success_url = reverse_lazy('flash_card:deck-list')

    success_message = '"%(title)s" was created successfully.'
    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            title=self.object.title,
        )

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)


class DeckListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    template_name = 'deck_list.html'
    queryset = Deck.objects.order_by('-updated_at')[:8]


class DeckDetailView(LoginRequiredMixin, DetailView):           # equal to CardListView
    template_name = 'deck_detail.html'      
    model = Deck

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d1 = Deck.objects.get(pk=self.kwargs.get('pk')) 
        context['card_list'] = d1.card_set.all()
        return context

    def get_object(self):
        deck = super().get_object()
        deck.view += 1
        deck.save()
        return deck


class DeckUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'deck_update.html'
    form_class = DeckCreateForm
    success_url = reverse_lazy('flash_card:deck-list')

    success_message = '"%(title)s" was updated successfully.'
    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            title=self.object.title,
        )

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Deck, pk=pk)

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)


class CardUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'card_update.html'
    form_class = CardCreateForm
    model = Card
    pk_url_kwarg = 'id'

    success_message = '"%(title)s" was updated successfully.'
    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            title=self.object.title,
        )

    def get_success_url(self):
        card = get_object_or_404(Card, id=self.kwargs.get('id'))
        return reverse('flash_card:deck-detail', kwargs={'pk': card.deck.pk})


class DeckDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'deck_delete.html'
    model = Deck
    success_url = reverse_lazy('flash_card:deck-list')

    success_message = '"%(title)s" was deleted successfully.'
    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            title=self.object.title,
        )


class CardDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'card_delete.html'
    model = Card
    pk_url_kwarg = 'id'

    def get_success_url(self):
        card = get_object_or_404(Card, id=self.kwargs.get('id'))
        return reverse('flash_card:deck-detail', kwargs={'pk': card.deck.pk})

flash_card/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        * {box-sizing: border-box;}
        
        .header {
          overflow: hidden;
          background-color: #18B698;
          padding: 20px 10px;
        }
        
        .header a {
          float: left;
          color: black;
          text-align: center;
          padding: 12px;
          text-decoration: none;
          font-size: 18px; 
          line-height: 25px;
          border-radius: 4px;
        }
        
        .header a.logo {
          font-size: 25px;
          font-weight: bold;
        }
        
        .header a:hover {
          background-color: #ddd;
          color: black;
        }
        
        .header a.active {
          background-color: dodgerblue;
          color: white;
        }
        
        .header-right {
          float: right;
        }

        </style>
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color: #CEF0E9;">
    <div class="header">
        <a href="{% url 'flash_card:deck-list' %}" class="logo" style="font-size: 37pt;">Casco</a>
        <div class="header-right">
          <a href="{% url 'flash_card:deck-list' %}">Home</a>
          <a href="{% url 'logout' %}">Logout</a>
        </div>
    </div>
      
    <div style="padding-left:20px">
        {% block content %}
        {% endblock %}
    </div>  
</body>
</html>

flash_card/templates/card_create.html
{% extends "base.html" %}

{% block title %}create new card{% endblock %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="add">
    </form>
{% endblock %

flash_card/templates/card_delete.html
{% extends "base.html" %}

{% block title %}delete card{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p style="font-size: 24pt;">Are you sure you want to delete <b>"{{object.title}}"</b>?</p>
        <p>
            <input type="submit" value="Delete">
            <a href="{% url 'flash_card:deck-detail' object.deck.pk %}"><input type="button" value="Cancel"></a>
        </p>
    </form>
{% endblock %}

flash_card/templates/card_update.html
{% extends "base.html" %}

{% block title %}update card{% endblock %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save changes">
    </form>
{% endblock %}

flash_card/templates/deck_create.html
{% extends "base.html" %}

{% block title %}create new card{% endblock %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="create">
    </form>
{% endblock %}

flash_card/templates/deck_delete.html
{% extends "base.html" %}

{% block title %}delete deck{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p style="font-size: 24pt;">Are you sure you want to delete <b>"{{object.title}}"</b> deck?</p>
        <p>
            <input type="submit" value="Delete">
            <a href="{% url 'flash_card:deck-list' %}"><input type="button" value="Cancel"></a>
        </p>
    </form>
{% endblock %}

flash_card/templates/deck_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}list of cards{% endblock %}

{% block content %}

<html>
  <head>
    <title></title>
    <meta content="">
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script>
      $(function() {
  $("#visible").click(function() {
      $('#invisible').toggleClass("show");
    });  
  });
    </script>
    <style>
      .hide{display:none;}
      .show{display:block;}
    </style>
  </head>
  <body>
    <p id="visible">{{item.title}}</p>
    <p id="invisible" class="hide">See me now!</p>
  </body>
</html>
<!-- ------------------------------------------------------------------- -->
<!DOCTYPE html>
<html>
<head>
<style>
.hide {
  display: none;
}
    
.myDIV:hover + .hide {
  display: block;
  color: rgb(0, 81, 255);
}
</style>
</head>
<body>
  {% if messages %}
    {% for message in messages %}
    <p style="font-size: large;">{{message}}</p>
    {% endfor %}
  {% endif %}
  <div style="float: right; margin-right: 10px; font-size: larger;"><a href="{% url 'flash_card:card-create' pk=object.pk %}">add a new card</a><br><br></div>
  <h2 style="font-size: 29pt;">{{object.title}}</h2>
  <div style="font-size: x-large;">{{object.description}}</div><br><br>
  {% for item in card_list %}
    {% if item.image %}
      <div style="width: 20%; height: 20%;"><img style="size: 50px; max-width:100%; max-height:100%;" src="{% static item.get_icon_folder %}" alt="card icon"></div>
    {% else %}
      <div style="width: 20%; height: 20%;"><img style="size: 50px; max-width:100%; max-height:100%;" src="{% static 'photos/default_card_image.png' %}" alt="default card icon"></div>
    {% endif %}
    <div class="myDIV" style="font-size: xx-large; width: 40%;">{{item.title}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <p style="font-size: medium; float: right;">created at:{{item.created_at}}</p></div>
    <div class="hide" style="font-size: xx-large;">{{item.answer}}</div>
    <div>
      <a href="{% url 'flash_card:card-delete' pk=item.deck.pk id=item.id %}"><input type="button" value="Delete"></a>
      <a href="{% url 'flash_card:card-update' pk=item.deck.pk id=item.id %}"><input type="button" value="Update"></a>
    </div>
    ------------------------------------------------------------------------------------------------------------------------<br>
  {% endfor %}

</body>
</html>

{% endblock %}

flash_card/templates/deck_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}list of decks{% endblock %}

{% block content %}

{% if messages %}
    {% for message in messages %}
    <p style="font-size: large;">{{message}}</p>
    {% endfor %}
{% endif %}

<div style="float: right; margin-right: 10px; font-size: larger;"><a href="{% url 'flash_card:deck-create' %}">create a new deck</a><br><br></div>
{% for item in object_list %}
    <div>
        <a href="{% url 'flash_card:deck-detail' item.pk %}">
            <div><h1>{{item.title}}<br></h1></div>
            {% if item.image %}
                <div style="width: 20%; height: 20%;"><img style="size: 50px; max-width:100%; max-height:100%;" src="{% static item.get_image_folder %}" alt="deck image"></div>
            {% else %}
                <div style="width: 20%; height: 20%;"><img style="size: 50px; max-width:100%; max-height:100%;" src="{% static 'photos/default_deck_image.png' %}" alt="default deck image"></div>
            {% endif %}
        </a>
        <div style="font-size: xx-large;">{{item.answer}}</div>
        <div style="font-size: medium;">views: {{item.view}}</div>
        <div>
            <a href="{% url 'flash_card:deck-delete' item.pk %}"><input type="button" value="Delete"></a>
            <a href="{% url 'flash_card:deck-update' item.pk %}"><input type="button" value="Update"></a>
        </div>
        -------------------------------------------------------------------<br>
    </div>     
{% endfor %}

{% endblock %}

flash_card/templates/deck_update.html
{% extends "base.html" %}

{% block title %}update deck{% endblock %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save changes">
    </form>
{% endblock %}